name: Deploy to S3

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and test steps here
      - name: Build and Test
        run: |
          # Add your build and test commands

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: af-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync client s3://plant-game-s3/client
